# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'crimescanner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  # Pods for crimescanner
end