// @flow
export const STATUS_BAR_LIGHT = 'light-content'
export const STATUS_BAR_DARK = 'dark-content'
export const KEYBOARD_COLOR_LIGHT = 'light'
export const KEYBOARD_COLOR_DARK = 'dark'
export const LOCAITON = 'location'
export const POLISEN_URI = 'https://polisen.se/api/events?'
export const LOCATION_URI_PART = 'locationname='
export const TYPE_URI_PART = 'type='
export const DATETIME_URI_PART = 'DateTime='
