// @flow

export const CRIME_TYPE: CrimeType = [
  {key: 'Alkohollagen', param: 'Alkohollagen', icon: '🍺'},
  {key: 'Anträffad död', param: 'Anträffad död', icon: '⚰️'},
  {key: 'Anträffat gods', param: 'Anträffad död', icon: '📦️'},
  {key: 'Arbetsplatsolycka', param: 'Arbetsplatsolycka', icon: '🚑'},
  {key: 'Bedrägeri', param: 'Bedrägeri', icon: '💸'},
  {key: 'Bombhot', param: 'Bombhot', icon: '💣'},
  {key: 'Brand', param: 'Brand;Brand automatlarm', icon: '🔥'},
  {key: 'Bråk', param: 'Bråk', icon: '💢'},
  {key: 'Detonation', param: 'Detonation', icon: '💥'},
  {key: 'Djur', param: 'Djur skadat/omhändertaget;Lagen om hundar och katter ', icon: '🦄'},
  {key: 'Ekobrott', param: 'Ekobrott', icon: '💵'},
  {key: 'Farligt föremål', param: 'Farligt föremål, misstänkt', icon: '⚠️'},
  {key: 'Fjällräddning', param: 'Fjällräddning', icon: '⛰️'},
  {key: 'Fylleri', param: 'Fylleri/LOB', icon: '🍺'},
  {key: 'Förfalskningsbrott', param: 'Förfalskningsbrott', icon: '💵'},
  {key: 'Försvunnen', param: 'Försvunnen person', icon: '👽'},
  {key: 'Gränskontroll', param: 'Gränskontroll', icon: '🛂'},
  {key: 'HäleriInbrott', param: 'HäleriInbrott', icon: '💰'},
  {key: 'Inbrott', param: 'Inbrott, försök;Larm Inbrott;Stöld/inbrott', icon: '🏠'},
  {key: 'Knivlagen', param: 'Knivlagen', icon: '🔪'},
  {key: 'Kontroll', param: 'Kontroll person/fordon ;Gränskontroll', icon: '🛑'},
  {key: 'Överfall', param: 'Larm Överfall', icon: '🙅'},
  {key: 'Miljöbrott', param: 'Miljöbrott', icon: '🥀'},
  {key: 'Missbruk av urkund ', param: 'Missbruk av urkund', icon: '📝'},
  {key: 'Misshandel', param: 'Misshandel;Misshandel, grov', icon: '👊'},
  {key: 'Mord', param: 'Mord;Mord/dråp;Mord/dråp, försök', icon: '☠️'},
  {key: 'Stöld', param: 'Stöld;Stöld, försök;Motorfordon, anträffat stulet;Motorfordon, stöld;Stöld, ringa;Stöld/inbrott', icon: '️️💰️'},
  {key: 'Narkotikabrott', param: 'Narkotikabrott', icon: '️️💊'},
  {key: 'Naturkatastrof', param: 'Naturkatastrof', icon: '️️🌊'},
  {key: 'Ofog barn/ungdom', param: 'Ofog barn/ungdom', icon: '👎'},
  {key: 'Ofredande/förargelse', param: 'Ofredande/förargelse', icon: '🤬'},
  {key: 'Olaga frihetsberövande', param: 'Olaga frihetsberövande', icon: '😱'},
  {key: 'Olaga hot', param: 'Olaga hot', icon: '🤬'},
  {key: 'Olaga intrång/hemfridsbrott', param: 'Olaga intrång/hemfridsbrott', icon: '🏠'},
  {key: 'Olovlig körning', param: 'Olovlig körning', icon: '🏁'},
  {key: 'Ordningslagen', param: 'Ordningslagen', icon: '☯️'},
  {key: 'Polisinsats/kommendering', param: 'Polisinsats/kommendering', icon: '👮️'},
  {key: 'Rattfylleri', param: 'Rattfylleri', icon: '🍸'},
  {key: 'Rån', param: 'Rån;Rån väpnat;Rån övrigt;Rån, försök', icon: '💰'},
  {key: 'Räddningsinsats', param: 'Räddningsinsats', icon: '🚒'},
  {key: 'Sammanfattning dag', param: 'Sammanfattning dag', icon: '✔️'},
  {key: 'Sammanfattning dygn', param: 'Sammanfattning dygn', icon: '✔️'},
  {key: 'Sammanfattning eftermiddag', param: 'Sammanfattning eftermiddag', icon: '✔️'},
  {key: 'Sammanfattning förmiddag', param: 'Sammanfattning förmiddag', icon: '✔️'},
  {key: 'Sammanfattning helg', param: 'Sammanfattning helg', icon: '✔️'},
  {key: 'Sammanfattning kväll', param: 'Sammanfattning kväll', icon: '✔️'},
  {key: 'Sammanfattning kväll och natt', param: 'Sammanfattning kväll och natt', icon: '✔️'},
  {key: 'Sammanfattning natt', param: 'Sammanfattning natt', icon: '✔️'},
  {key: 'Sammanfattning vecka', param: 'Sammanfattning vecka', icon: '✔️'},
  {key: 'Sedlighetsbrott', param: 'Sedlighetsbrott', icon: '🍆'},
  {key: 'Sjukdom/olycksfall', param: 'Sjukdom/olycksfall', icon: '⛑️'},
  {key: 'Sjölagen', param: 'Sjölagen', icon: '🚣'},
  {key: 'Skadegörelse', param: 'Skadegörelse', icon: '👎'},
  {key: 'Skottlossning', param: 'Skottlossning;Skottlossning, misstänkt', icon: '🔫'},
  {key: 'Spridning smittsamma kemikalier', param: 'Spridning smittsamma kemikalier', icon: '🛢️'},
  {key: 'Tillfälligt obemannat', param: 'Tillfälligt obemannat', icon: '❓'},
  {key: 'Trafikbrott', param: 'Trafikbrott', icon: '⛔'},
  {key: 'Trafikhinder', param: 'Trafikhinder', icon: '🚧'},
  {key: 'Trafikkontroll', param: 'Trafikkontroll', icon: '✋'},
  {key: 'Trafikolycka', param: 'Trafikolycka;Trafikolycka, personskada;Trafikolycka, singel;Trafikolycka, smitning från;Trafikolycka, vilt', icon: '🚨'},
  {key: 'Uppdatering', param: 'Uppdatering', icon: '👮️'},
  {key: 'Utlänningslagen', param: 'Utlänningslagen', icon: '✈️'},
  {key: 'Vapenlagen', param: 'Vapenlagen', icon: '🔫'},
  {key: 'Varningslarm', param: 'Varningslarm/haveri', icon: '🔔'},
  {key: 'Våld/hot mot tjänsteman', param: 'Våld/hot mot tjänsteman', icon: '💂'},
  {key: 'Våldtäkt', param: 'Våldtäkt;Våldtäkt, försök', icon: '🙅'},
  {key: 'Vållande till kroppsskada', param: 'Vållande till kroppsskada', icon: '🤕'}
]
